version: '2'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: localhost
    ports:
      - "27017:27017"

  user-management-service:
    build: user-management-service/
    depends_on:
      - mysql
    restart: always
    network_mode: "host"
    image: user-management-service
    hostname: localhost
    ports:
      - 9000:9000

  user-stock-favourite-service:
    build: user-stock-favourite-service/
    depends_on:
      - mongodb
    restart: always
    network_mode: "host"
    image: user-stock-favourite-service
    hostname: localhost
    ports:
      - 8084:8084

  search-service:
    build: search-service/
    restart: always
    network_mode: "host"
    image: search-service
    hostname: localhost
    ports:
      - 8075:8075
